/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tema8.Ejercicios.Ficheros.Ejercicio4;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.DataInputStream;
import java.io.EOFException;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;

/**
 *
 * @author bladiaju
 */
public class app2 extends javax.swing.JFrame {
    
    private File fileTexto;
    private File fileDatos;
    private String rutaCarpetaCartas = "";
    
    
    private DataInputStream dis;
    private BufferedReader br;
    private BufferedWriter bw;
    
    /**
     * Creates new form app2
     */
    public app2() {
        initComponents();
        setFrame();
    }

    public void setFrame(){
        this.setTitle("Generador de cartas");
        this.btn_generar.setMnemonic('G');
    }
    
    public File seleccionarFile(String titulo, String textoFiltro, String extFiltro) {

        JFileChooser jfc = new JFileChooser("C:\\Ejercicios\\Programacion\\Ejercicios\\src\\Tema8\\Ejercicios\\Ficheros\\Ejercicio4");
        jfc.setDialogTitle(titulo);
        FileNameExtensionFilter filter = new FileNameExtensionFilter(textoFiltro, extFiltro);
        jfc.addChoosableFileFilter(filter);
        File file = null; //referencia al archivo
        int resp = jfc.showOpenDialog(this);
        if (resp == JFileChooser.APPROVE_OPTION) {
            file = jfc.getSelectedFile();
        }
        return file;
    }
    
    public File seleccionarCarpetaDestino() {

        JFileChooser jfc = new JFileChooser("C:\\Ejercicios\\Programacion\\Ejercicios\\src\\Tema8\\Ejercicios\\Ficheros\\Ejercicio4");
        jfc.setDialogTitle("Carpea donde dejar las cartas generadas");
        jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        File file = null; //referencia a la carpeta
        int resp = jfc.showOpenDialog(this);
        if (resp == JFileChooser.APPROVE_OPTION) {
            file = jfc.getSelectedFile();
        }
        return file;
    }
    
    public String carpetaCartas() {

        JFileChooser jfc = new JFileChooser("C:\\Ejercicios\\Programacion\\Ejercicios\\src\\Tema8\\Ejercicios\\Ficheros\\Ejercicio4");
        jfc.setDialogTitle("Carpea donde dejar las cartas generadas");
        jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        File file = null; //referencia a la carpeta
        int resp = jfc.showOpenDialog(this);
        if (resp == JFileChooser.APPROVE_OPTION) {
            file = jfc.getSelectedFile();
        }
        return file.getAbsolutePath();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        texto_texto = new javax.swing.JTextField();
        texto_datos = new javax.swing.JTextField();
        btn_generar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_aplicacion = new javax.swing.JMenu();
        item_salir = new javax.swing.JMenuItem();
        menu_ficheros = new javax.swing.JMenu();
        item_texto = new javax.swing.JMenuItem();
        item_datos = new javax.swing.JMenuItem();
        menu_cartas = new javax.swing.JMenu();
        item_generar = new javax.swing.JMenuItem();
        item_generaraPDF = new javax.swing.JMenuItem();
        item_ver = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Fichero texto:");

        jLabel2.setText("Fichero datos:");

        texto_texto.setToolTipText("Doble click para seleccionar el fichero con los datos");
        texto_texto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                texto_textoMouseClicked(evt);
            }
        });

        texto_datos.setToolTipText("Doble click para seleccionar el fichero con los datos");
        texto_datos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                texto_datosMouseClicked(evt);
            }
        });

        btn_generar.setMnemonic('G');
        btn_generar.setText("Generar Cartas");
        btn_generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generarActionPerformed(evt);
            }
        });

        menu_aplicacion.setText("Aplicacion");

        item_salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        item_salir.setText("Salir");
        item_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_salirActionPerformed(evt);
            }
        });
        menu_aplicacion.add(item_salir);

        jMenuBar1.add(menu_aplicacion);

        menu_ficheros.setText("Fichero");

        item_texto.setText("Texto");
        item_texto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_textoActionPerformed(evt);
            }
        });
        menu_ficheros.add(item_texto);

        item_datos.setText("Datos");
        item_datos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_datosActionPerformed(evt);
            }
        });
        menu_ficheros.add(item_datos);

        jMenuBar1.add(menu_ficheros);

        menu_cartas.setText("Cartas");

        item_generar.setText("Generar cartas (txt)");
        menu_cartas.add(item_generar);

        item_generaraPDF.setText("Generar cartas (pdf)");
        item_generaraPDF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item_generaraPDFMouseClicked(evt);
            }
        });
        menu_cartas.add(item_generaraPDF);

        item_ver.setText("Ver");
        item_ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_verActionPerformed(evt);
            }
        });
        menu_cartas.add(item_ver);

        jMenuBar1.add(menu_cartas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(texto_datos, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                            .addComponent(texto_texto)))
                    .addComponent(btn_generar, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(texto_texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(texto_datos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_generar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void item_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_item_salirActionPerformed

    private void item_textoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_textoActionPerformed
        fileTexto = seleccionarFile("Selecciona la carta con el texto", "Ficheros de texto", "txt");
    }//GEN-LAST:event_item_textoActionPerformed

    private void item_datosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_datosActionPerformed
        fileDatos = seleccionarFile("Selecciona el fichero con los empleados", "Ficheros binarios", "dat");
    }//GEN-LAST:event_item_datosActionPerformed

    private void texto_textoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texto_textoMouseClicked
        if(evt.getClickCount() == 2){
            fileTexto = seleccionarFile("Selecciona la carta con el texto", "Ficheros de texto", "txt");
            if(fileTexto != null) this.texto_texto.setText(fileTexto.getPath());
        }
    }//GEN-LAST:event_texto_textoMouseClicked

    private void texto_datosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texto_datosMouseClicked
        if(evt.getClickCount() == 2){
            fileDatos = seleccionarFile("Selecciona la carta con los empleados", "Ficheros de binarios", "dat");
            if(fileDatos != null) this.texto_datos.setText(fileDatos.getPath());
        }
    }//GEN-LAST:event_texto_datosMouseClicked

    private void btn_generarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generarActionPerformed
        File carpetaDestino = seleccionarCarpetaDestino();
        if(carpetaDestino == null){
            JOptionPane.showMessageDialog(this, "Debe seleccionar una carpeta destino de las cartas", "Aviso",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(fileTexto == null || fileDatos == null){
            JOptionPane.showMessageDialog(this, "Debe seleccionar los ficheros con los datos", "Aviso",JOptionPane.WARNING_MESSAGE);
            return;
        }
        //proceso de generación de las cartas
        boolean EOF = false;
        try(InputStream input = Files.newInputStream(Paths.get(fileDatos.toURI()));
                DataInputStream dis = new DataInputStream(input)){
            //extraemos texto de la carta
            String texto = extraerTexto();
            String archivoFelicitacion = ""; //nombre archivo con la carta de felicitacion
            int cont = 0; //contador secuencial del nº de la carta
            
            String nombreEmp = "";
            String direccEmp = "";
            while(!EOF){
                //Hay empleado
                cont++;
                nombreEmp = dis.readUTF();
                direccEmp = dis.readUTF();
                
                //Genero archivo con la carta
                archivoFelicitacion = "carta" + cont + ".txt";
                BufferedWriter bw = Files.newBufferedWriter(Paths.get(carpetaDestino.getPath() + File.separator+archivoFelicitacion));
                
                //escribo los datos en la carta
                bw.write(nombreEmp);
                bw.newLine();
                bw.newLine();
                bw.write(direccEmp + "\t\t" + fecha("Valladolid"));
                bw.newLine();
                bw.newLine();
                bw.write(texto);
                
                //cierro el flujo de salida
                bw.close();
            }
            
        } catch (EOFException ex) {
            JOptionPane.showMessageDialog(this, "Cartas generadas", "Información", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(), "ERROR", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_btn_generarActionPerformed

    private void item_generaraPDFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item_generaraPDFMouseClicked
        
    }//GEN-LAST:event_item_generaraPDFMouseClicked

    private void item_verActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_verActionPerformed
        rutaCarpetaCartas = carpetaCartas();
        JOptionPane.showMessageDialog(this, rutaCarpetaCartas);
    }//GEN-LAST:event_item_verActionPerformed
    
    private String extraerTexto() throws IOException{
        List<String> texto = Files.readAllLines(Paths.get(fileTexto.toURI()), StandardCharsets.ISO_8859_1);
        String todo = "";
        for(String linea:texto){
            todo += linea + "\n";
        }
        return todo;
    }
    
    private String fecha(String localidad){
        DateTimeFormatter dtf = DateTimeFormatter.ISO_LOCAL_DATE;
        return localidad + ", " + dtf.format(LocalDate.now());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(app2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(app2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(app2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(app2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new app2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_generar;
    private javax.swing.JMenuItem item_datos;
    private javax.swing.JMenuItem item_generar;
    private javax.swing.JMenuItem item_generaraPDF;
    private javax.swing.JMenuItem item_salir;
    private javax.swing.JMenuItem item_texto;
    private javax.swing.JMenuItem item_ver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menu_aplicacion;
    private javax.swing.JMenu menu_cartas;
    private javax.swing.JMenu menu_ficheros;
    private javax.swing.JTextField texto_datos;
    private javax.swing.JTextField texto_texto;
    // End of variables declaration//GEN-END:variables
}
