
package Tema9.Ejercicios;

import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Random;
import javax.swing.JButton;
import javax.swing.JFrame;

/**
 *
 * @author bladiaju
 */
public class Pin extends javax.swing.JFrame implements MouseListener{

    /**
     * Creates new form Pin
     */
    private String texto = "";
    
    public Pin() {
        initComponents();
        setFrame();
        setBotonesLayout();
    }
    private void setFrame(){
        this.setTitle("Generador de Pin");
        this.setResizable(false);
        this.setSize(500, 200);
    }
    private void creacionBotones(){
        ArrayList<Integer> lista = new ArrayList();
        Random gen = new Random();
        while(lista.size() < 10){
            int num = gen.nextInt(0,10);
            if(!lista.contains(num)){
                lista.add(num);
            }
        }
        
        for (int i = 0; i < 10; i++) {
            JButton boton = new JButton(String.valueOf(lista.get(i)));
            boton.addMouseListener(this);
            this.panelBotones.add(boton); 
        }
    }
    
    private void setBotonesLayout(){
        creacionBotones();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBotones = new javax.swing.JPanel();
        panelTexto = new javax.swing.JPanel();
        texto_pin = new javax.swing.JPasswordField();
        boton_ver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(panelBotones, java.awt.BorderLayout.PAGE_START);

        panelTexto.setLayout(new javax.swing.BoxLayout(panelTexto, javax.swing.BoxLayout.LINE_AXIS));
        panelTexto.add(texto_pin);

        boton_ver.setText("Ver");
        panelTexto.add(boton_ver);

        getContentPane().add(panelTexto, java.awt.BorderLayout.PAGE_END);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_ver;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelTexto;
    private javax.swing.JPasswordField texto_pin;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {
        if(!((JButton) e.getSource()).getText().equals("Ver")){
            texto += ((JButton) e.getSource()).getText();
            texto_pin.setText(texto);
        }
    }

    @Override
    public void mousePressed(MouseEvent e) {
        if((((JButton) e.getSource()).getText()).equals("Ver")){
            texto_pin.setEchoChar((char)0);
        }
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        
    }

    @Override
    public void mouseExited(MouseEvent e) {
        
    }
}
