/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gf.encuesta;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import com.opencsv.CSVParser;
import com.opencsv.CSVParserBuilder;
import com.opencsv.CSVReader;
import com.opencsv.CSVReaderBuilder;
import com.opencsv.CSVWriter;
import com.opencsv.CSVWriterBuilder;
import com.opencsv.ICSVWriter;
import com.opencsv.exceptions.CsvException;
import com.opencsv.exceptions.CsvValidationException;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Reader;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author bladiaju
 */
public class Ventana extends javax.swing.JFrame {
    
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        setFrame();
    }
    
    private int votosSi;
    private int votosNo;
    private int votosNc;
    
    
    private void setFrame(){
       
        this.setLocationRelativeTo(null);
        this.setTitle("Encuesta");
        this.setSize(387, 245);
        this.setResizable(false);
        this.rboton_si.setSelected(true);
    }
    public static CSVParser parser = new CSVParserBuilder().withSeparator(';').withIgnoreQuotations(true).build();
    
    private void lecturaCSV(Reader reader) throws IOException, CsvException{
        DecimalFormat df = new DecimalFormat("0.00");
        try (CSVReader csvreader = new CSVReaderBuilder(reader).withCSVParser(parser).build()){
            String [] linea; //Cada linea leida del fichero CSV
            String texto = "";
            while((linea = csvreader.readNext()) != null){
                int numVotos = (Integer.parseInt(linea[0]) + Integer.parseInt(linea[1]) + Integer.parseInt(linea[2]));
                texto += "Numero de votos: " + numVotos + "\n";
                texto += "Porcentaje de SI: " + df.format((Integer.parseInt(linea[0]) / (double) numVotos)*100) + "%\n";
                texto += "Porcentaje de SI: " + df.format((Integer.parseInt(linea[1]) / (double) numVotos)*100) + "%\n";
                texto += "Porcentaje de SI: " + df.format((Integer.parseInt(linea[2]) / (double) numVotos)*100) + "%\n";
            }
            DateTimeFormatter formato = DateTimeFormatter.ofPattern("HH:mm dd/MM/yyyy");
            LocalDateTime fecha = LocalDateTime.now();
            JOptionPane.showMessageDialog(this, texto,String.valueOf(formato.format(fecha)),JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    private void escrituraCSV() throws IOException{
        try (ICSVWriter cw = new CSVWriterBuilder(new FileWriter(".\\src\\main\\java\\com\\gf\\encuesta\\ficheros\\encuesta.csv" , true)).withQuoteChar(CSVWriter.NO_QUOTE_CHARACTER).withSeparator(';').withLineEnd(CSVWriter.DEFAULT_LINE_END).build()){
            if(rboton_si.isSelected()){
                ++votosSi;
            } else if(rboton_no.isSelected()){
                ++votosNo;
            } if(rboton_nc.isSelected()){
                ++votosNc;
            }
            String [] texto = {String.valueOf(votosSi),String.valueOf(votosNo),String.valueOf(votosNc)};
            cw.writeNext(texto);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo_opciones = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        rboton_si = new javax.swing.JRadioButton();
        rboton_no = new javax.swing.JRadioButton();
        rboton_nc = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        boton_votar = new javax.swing.JButton();
        boton_resultados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("¿Crees que los viernes hay que venir a clase?");
        jPanel4.add(jLabel1);

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.GridLayout(3, 0));

        grupo_opciones.add(rboton_si);
        rboton_si.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rboton_si.setText("Si");
        rboton_si.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(rboton_si);

        grupo_opciones.add(rboton_no);
        rboton_no.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rboton_no.setText("No");
        rboton_no.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(rboton_no);

        grupo_opciones.add(rboton_nc);
        rboton_nc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rboton_nc.setText("NS / NC");
        rboton_nc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(rboton_nc);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridLayout(2, 0));

        boton_votar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        boton_votar.setForeground(new java.awt.Color(255, 0, 51));
        boton_votar.setMnemonic('V');
        boton_votar.setText("Votar");
        boton_votar.setMaximumSize(new java.awt.Dimension(20, 23));
        boton_votar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_votarActionPerformed(evt);
            }
        });
        jPanel2.add(boton_votar);

        boton_resultados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        boton_resultados.setForeground(new java.awt.Color(255, 0, 51));
        boton_resultados.setMnemonic('R');
        boton_resultados.setText("Resultados de la encuesta");
        boton_resultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_resultadosActionPerformed(evt);
            }
        });
        jPanel2.add(boton_resultados);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_votarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_votarActionPerformed
        
        try (BufferedWriter bw = new BufferedWriter(new FileWriter(".\\src\\main\\java\\com\\gf\\encuesta\\ficheros\\encuesta.csv"))){
            escrituraCSV();
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "No se ha encontrado el archivo.","ERROR",JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex){
            JOptionPane.showMessageDialog(this, "No se ha leido el archivo.","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_boton_votarActionPerformed

    private void boton_resultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_resultadosActionPerformed
        try (BufferedReader br = new BufferedReader(new FileReader(".\\src\\main\\java\\com\\gf\\encuesta\\ficheros\\encuesta.csv"))){
            lecturaCSV(br);
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "No se ha encontrado el archivo.","ERROR",JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex){
            JOptionPane.showMessageDialog(this, "No se ha escrito el archivo.","ERROR",JOptionPane.ERROR_MESSAGE);
        } catch (CsvValidationException ex){
            JOptionPane.showMessageDialog(this, "ERROR","ERROR",JOptionPane.ERROR_MESSAGE);
        } catch (CsvException ex) {
            JOptionPane.showMessageDialog(this, "ERROR","ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_boton_resultadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_resultados;
    private javax.swing.JButton boton_votar;
    private javax.swing.ButtonGroup grupo_opciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton rboton_nc;
    private javax.swing.JRadioButton rboton_no;
    private javax.swing.JRadioButton rboton_si;
    // End of variables declaration//GEN-END:variables
}
