/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tema7.Ejercicios.Agenda;

import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;

/**
 *
 * @author bladiaju
 */
public class AppAgenda extends javax.swing.JFrame {
    ArrayList <Contacto> listaContactos = new ArrayList();
    
    /**
     * Creates new form AppAgenda
     */
    public AppAgenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        resultado = new javax.swing.JTextArea();
        botonCrear = new javax.swing.JButton();
        botonBuscar = new javax.swing.JButton();
        botonModificar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        botonMostrar = new javax.swing.JButton();
        botonVaciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        resultado.setColumns(20);
        resultado.setRows(5);
        jScrollPane1.setViewportView(resultado);

        botonCrear.setText("Crear Contacto");
        botonCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCrearMouseClicked(evt);
            }
        });

        botonBuscar.setText("Buscar Contacto");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        botonModificar.setText("Modificar Contacto");
        botonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarActionPerformed(evt);
            }
        });

        botonEliminar.setText("Eliminar Contacto");

        botonMostrar.setText("Mostrar Contactos");
        botonMostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonMostrarMouseClicked(evt);
            }
        });

        botonVaciar.setText("Vaciar Contacto");
        botonVaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVaciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonBuscar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonVaciar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonCrear))
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonEliminar)
                            .addComponent(botonMostrar)
                            .addComponent(botonModificar))
                        .addContainerGap(19, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonCrear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(botonModificar)
                        .addGap(18, 18, 18)
                        .addComponent(botonEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(botonMostrar)
                        .addGap(18, 18, 18)
                        .addComponent(botonVaciar)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarActionPerformed
        busquedaContacto(listaContactos);
    }//GEN-LAST:event_botonModificarActionPerformed

    private void botonCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCrearMouseClicked
        Contacto c = new Contacto(JOptionPane.showInputDialog(null, "Nombre: ", "CONTACTO", 1));
        String telefono = JOptionPane.showInputDialog(null, "Telefono: ", "CONTACTO", 1);
        if(!telefono.equals("")){
            c.setTelefono(Integer.parseInt(telefono));
        }
        listaContactos.add(c);
        c.setIdContacto(listaContactos.indexOf(c));
    }//GEN-LAST:event_botonCrearMouseClicked

    private void botonMostrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMostrarMouseClicked
        imprimirLista(listaContactos);
    }//GEN-LAST:event_botonMostrarMouseClicked

    private void botonVaciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVaciarActionPerformed
        int opcion = JOptionPane.showConfirmDialog(null, "Deseas vaciar la agenda", "VACIAR", 0, 2, null);
        if(opcion == 0){
           listaContactos.clear();
           resultado.setText("");
        }
        
    }//GEN-LAST:event_botonVaciarActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        busquedaContacto(listaContactos);
        
    }//GEN-LAST:event_botonBuscarActionPerformed
    
    
    public void imprimirLista(ArrayList<Contacto> lista){
        String elementos = "";
        for(Contacto c: lista){
            elementos = elementos + c.toString() +"\n";
        }
        resultado.setText(elementos);
    }
    
    public void busquedaContacto(ArrayList<Contacto> lista){
        String opcionArray[] = {"Nombre", "Telefono"};
        int opcion = JOptionPane.showOptionDialog(null, "Ordenar por nombre o por telefono", "ORDEN", 0, 1 , null, opcionArray, null);
        System.out.println(opcion);
        if(opcion == 0){
            String elementos = "";
            int cont = 0;
            Contacto key = new Contacto(JOptionPane.showInputDialog(null, "Nombre a buscar: ", "BUSQUEDA", 1));
            for(Contacto c: lista){
                if(key.getNombre().equals(c.getNombre())){
                    elementos = elementos + c.toString() +"\n";
                    key.setIdContacto(c.getIdContacto());
                    cont++;
                }
            }
            resultado.setText(elementos);
        } else{
            String elementos = "";
            int cont = 0;
            Contacto key = new Contacto("");
            key.setTelefono(Integer.parseInt(JOptionPane.showInputDialog(null, "Telefono: ", "CONTACTO", 1)));
            for(Contacto c: lista){
                if(key.getTelefono() == c.getTelefono()){
                    elementos = elementos + c.toString() +"\n";
                    key.setIdContacto(c.getIdContacto());
                    cont++;
                }
            }
            resultado.setText(elementos);
        }
    }
//        if(cont == 0){
//            JOptionPane.showMessageDialog(null, "No existe ningún contacto con ese nombre");
//        } else if(cont == 1){
//            key.setNombre(JOptionPane.showInputDialog(null, "Nombre: ", "CONTACTO", 1));
//            String telefono = JOptionPane.showInputDialog(null, "Telefono: ", "CONTACTO", 1);
//            if(!telefono.equals("")){
//                key.setTelefono(Integer.parseInt(telefono));
//            }
//            lista.set(key.getIdContacto(), key);
//        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppAgenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonCrear;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonModificar;
    private javax.swing.JButton botonMostrar;
    private javax.swing.JButton botonVaciar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea resultado;
    // End of variables declaration//GEN-END:variables
}
