/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tema10.Ejemplos;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JLabel;

/**
 *
 * @author macarena
 *
 * Ejemplo de uso de Metadatos.
 *
 * Para ello se utilizará una base de datos relacional MySQL.
 * La conexión a la bd se hará utilizando el usuario root sin contraseña.
 *
 * OPERATIVA: En el constructor de la ventana se recuperan los metadatos tanto de la bd como de la tabla.
 * Con ellos se pone información en el título de la ventana, y también se recuperan los nombres de las columnas
 * de la tabla, y sus tipos al pulsar el botón Aceptar.
 *
 */
public class EjemploMetadata extends javax.swing.JFrame {

    private String url = "jdbc:mysql://localhost:3306/dam";
    private ResultSetMetaData rsmd; //metadatos del resultado de una SELECT
    private DatabaseMetaData dbmd; //metadatos de toda la BD
    private String nombre_bd;
    private String nombre_tabla;
    private String nombre_usuario;

    public EjemploMetadata(java.awt.Frame parent, boolean modal) {
        initComponents();
        recuperarMetaDatos();
        //actualizo el título de la ventana con los metadatos
        this.setTitle("Usuario: " + nombre_usuario + "  BD: " + nombre_bd + " --> " + nombre_tabla);
        this.pack(); //actualizo el tamañan de la ventana después de meter los checkbox
        this.setLocationRelativeTo(null);
    }

    private void recuperarMetaDatos() {
        try ( Connection con = DriverManager.getConnection(url, "root", "");) {
            dbmd = con.getMetaData(); //recuperamos los metadatos de la bd
            //le uso para
            nombre_bd = dbmd.getURL();
            nombre_usuario = dbmd.getUserName();

            //ahora recuperao los metadatos de la tabla
            try ( Statement st = con.createStatement();) {
                String sql = "SELECT * FROM alumnos";
                try ( ResultSet rs = st.executeQuery(sql);) {
                    rsmd = rs.getMetaData(); //recupero los metadatos de la tabla1
                    
                    nombre_tabla = rsmd.getTableName(1);
                    //creo una etiqueta para cada columna y le añado al panel correspondiente de la ventana
                    String separador = "\t-\t"; //separador de columnas
                    for (int i = 1; i <= rsmd.getColumnCount(); i++) {
                        if (i == rsmd.getColumnCount()) {
                            separador = ""; //para que no saque el guión en la última columna
                        }
                        JLabel label = new JLabel(rsmd.getColumnLabel(i) + separador); //creo la etiqueta
                        panelColumnas.add(label); //la añado al panel para que se vea
                    }
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelColumnas = new javax.swing.JPanel();
        panelInfo = new javax.swing.JPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        panelBotones = new javax.swing.JPanel();
        botonAceptar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 800, 250));
        setMinimumSize(new java.awt.Dimension(800, 250));

        jPanel1.setLayout(new java.awt.GridLayout(0, 1));

        panelColumnas.setBorder(javax.swing.BorderFactory.createTitledBorder("Columnas"));
        jPanel1.add(panelColumnas);

        panelInfo.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        panelInfo.setLayout(new javax.swing.BoxLayout(panelInfo, javax.swing.BoxLayout.LINE_AXIS));
        panelInfo.add(filler2);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("TIPOS:");
        jLabel1.setPreferredSize(new java.awt.Dimension(50, 14));
        panelInfo.add(jLabel1);
        panelInfo.add(jTextField1);

        jPanel1.add(panelInfo);

        panelBotones.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 50, 1, 50));

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });
        panelBotones.add(botonAceptar);

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });
        panelBotones.add(botonCancelar);

        jPanel1.add(panelBotones);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Muestra los tipos de las columnas en la caja de texto. Para ello usa los metadatos de la tabla.
    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        try {
            String info = "";
            String separador = " - ";
            for (int i = 1; i <= rsmd.getColumnCount(); i++) {
                if (i == rsmd.getColumnCount()) {
                    separador = "";
                }
                String tipo = String.valueOf(rsmd.getColumnTypeName(i)) + separador;
                info += tipo;
            }
            this.jTextField1.setText(info);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EjemploMetadata.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EjemploMetadata.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EjemploMetadata.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EjemploMetadata.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EjemploMetadata dialog = new EjemploMetadata(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelColumnas;
    private javax.swing.JPanel panelInfo;
    // End of variables declaration//GEN-END:variables

}
