/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tema10.Ejemplos;

import java.awt.Dimension;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.RowSorter;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author macarena
 */
public class EjemploTable extends javax.swing.JFrame implements TableModelListener {

    private DefaultTableModel modeloTabla;
    private String url = "jdbc:mysql://localhost:3306/dam";
    private String[] columnas;

    public EjemploTable() {
        initComponents();
        setTabla();
        setFrame();
    }

    private void setFrame() {
        this.setTitle("Ejemplo JTable");
        this.setPreferredSize(new Dimension(500, 180));
        this.setLocationRelativeTo(null);
        this.pack();
    }

    private void setTabla() {
        this.jTable1.setSelectionBackground(java.awt.Color.pink);
        this.jTable1.setModel(new DefaultTableModel(getDatos(), columnas));
        this.modeloTabla = (DefaultTableModel) this.jTable1.getModel();
        RowSorter<TableModel> sorter = new TableRowSorter<>(this.modeloTabla);
        this.jTable1.setRowSorter(sorter);
        this.modeloTabla.addTableModelListener(this);
    }

    //Devolvermos la matriz con los datos de la JTable
    private Object[][] getDatos() {
        Object[][] obj = null;

        try (Connection con = DriverManager.getConnection(url, "root", "")) {
            //ahora recuperao los metadatos de la tabla
            try (Statement st = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE)) {
                String sql = "SELECT * FROM alumnos";
                try (ResultSet rs = st.executeQuery(sql)) {
                    ResultSetMetaData rsmd = rs.getMetaData(); //recupero los metadatos de la tabla1

                    rs.last();
                    int numCols = rsmd.getColumnCount();
                    int numFils = rs.getRow();

                    obj = new Object[numFils][numCols];
                    setColumnas(rsmd);
                    int j = 0;
                    rs.beforeFirst();
                    while (rs.next()) {
                        for (int i = 0; i < numCols; i++) {
                            obj[j][i] = rs.getObject(i + 1);
                        }
                        j++;
                    }

                } catch (SQLException ex) {
                    Logger.getLogger(EjemploTable.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (SQLException ex) {
                Logger.getLogger(EjemploTable.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (SQLException ex) {
            Logger.getLogger(EjemploTable.class.getName()).log(Level.SEVERE, null, ex);
        }
        return obj;
    }

    //Establecemos los nombres de las columnas de la JTable
    private void setColumnas(ResultSetMetaData rsmd) {
        try {
            columnas=new String[rsmd.getColumnCount()];
            for(int i=1;i<=rsmd.getColumnCount();i++){
                columnas[i-1]=rsmd.getColumnLabel(i);
            }
        } catch (SQLException ex) {
            Logger.getLogger(EjemploTable.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return colIndex != 0;
            }
        };

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

   @Override
    public void tableChanged(TableModelEvent tme) {
        //algún valor de la tabla se ha actualizado
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EjemploTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EjemploTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EjemploTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EjemploTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EjemploTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
