
package com.gf.practica3eva.Vistas;

import com.gf.practica3eva.Conexion.Conexion;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.DefaultComboBoxModel;

/**
 * Ventana para elegir usuario de la base de datos
 * @author Juan Jose Blanco Diaz y Alejandro Francos Fernandez
 * @since 04-06-2024
 * @version 1.0
 */
public class SeleccionUsuario extends javax.swing.JDialog implements KeyListener{

    /**
     * Creates new form Vista
     */
    
    private DefaultComboBoxModel <String> modeloTipo = new DefaultComboBoxModel();
    private static VistaPrincipal vp;
    
    
    public SeleccionUsuario(VistaPrincipal parent, boolean modal) {
        super(parent, modal);
        this.vp = parent;
        initComponents();
        setFrame();
    }
    
    private void setFrame(){
        this.setTitle("Selector Ususario");
        this.setLocationRelativeTo(null);
        this.setSize(525,230);
        this.setResizable(false);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        modeloTipo.addElement("MySQL");
        modeloTipo.addElement("Oracle");
        selector_tipo.setToolTipText("Selecciona el tipo de base de datos");
        texto_usuario.setToolTipText("Escribe el usuario de la base de datos");
        texto_contrasena.setToolTipText("Escribe la contraseña de la base de datos");
        texto_hostname.setToolTipText("Escribe el hostname de la base de datos");
        texto_puerto.setToolTipText("Escribe el puerto de la base de datos");
        selector_tipo.setModel(modeloTipo);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("./src/main/java/com/gf/practica3eva/Resources/icono.png"));
        setKeyListener();
    }
    private void setKeyListener(){
        this.btn_conectar.addKeyListener(this);
        this.btn_cerrar.addKeyListener(this);
        this.texto_contrasena.addKeyListener(this);
        this.texto_hostname.addKeyListener(this);
        this.texto_puerto.addKeyListener(this);
        this.texto_usuario.addKeyListener(this);
        this.selector_tipo.addKeyListener(this);
    }
    
    private void realizarConexion(){
        Conexion conn = new Conexion();
        conn.setTipo(String.valueOf(selector_tipo.getSelectedItem()));
        conn.setUser(texto_usuario.getText());
        conn.setPassword(texto_contrasena.getText());
        conn.setHostname(texto_hostname.getText());
        conn.setPuerto(texto_puerto.getText());
        if(this.selector_tipo.getSelectedItem().equals("MySQL")){
            conn.setUrl(String.valueOf(this.selector_tipo.getSelectedItem()));
        } else {
            conn.setUrl(String.valueOf(this.selector_tipo.getSelectedItem()));
            System.out.println(conn.getUrl());
        }
        vp.setConexion(conn);
        this.dispose();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        selector_tipo = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        texto_usuario = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        texto_contrasena = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        texto_hostname = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        texto_puerto = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        btn_conectar = new javax.swing.JButton();
        btn_cerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(0, 1));

        jPanel2.setLayout(new java.awt.BorderLayout(63, 0));

        jPanel2.add(selector_tipo, java.awt.BorderLayout.CENTER);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("   Tipo");
        jPanel2.add(jLabel5, java.awt.BorderLayout.LINE_START);

        jPanel1.add(jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout(38, 0));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("   Usuario:");
        jPanel3.add(jLabel1, java.awt.BorderLayout.LINE_START);
        jPanel3.add(texto_usuario, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3);

        jPanel4.setLayout(new java.awt.BorderLayout(10, 0));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setText("   Contraseña:");
        jPanel4.add(jLabel2, java.awt.BorderLayout.LINE_START);
        jPanel4.add(texto_contrasena, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout(18, 0));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("   Hostname:");
        jPanel5.add(jLabel3, java.awt.BorderLayout.LINE_START);
        jPanel5.add(texto_hostname, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel5);

        jPanel6.setLayout(new java.awt.BorderLayout(45, 0));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setText("   Puerto:");
        jPanel6.add(jLabel4, java.awt.BorderLayout.LINE_START);
        jPanel6.add(texto_puerto, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel6);

        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btn_conectar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btn_conectar.setText("Conectar");
        btn_conectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_conectarActionPerformed(evt);
            }
        });
        jPanel7.add(btn_conectar);

        btn_cerrar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btn_cerrar.setText("Cerrar");
        btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarActionPerformed(evt);
            }
        });
        jPanel7.add(btn_cerrar);

        jPanel1.add(jPanel7);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_conectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_conectarActionPerformed
        realizarConexion();
    }//GEN-LAST:event_btn_conectarActionPerformed

    private void btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeleccionUsuario(vp, true).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cerrar;
    private javax.swing.JButton btn_conectar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    protected javax.swing.JComboBox selector_tipo;
    private javax.swing.JTextField texto_contrasena;
    private javax.swing.JTextField texto_hostname;
    protected javax.swing.JTextField texto_puerto;
    private javax.swing.JTextField texto_usuario;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void keyPressed(KeyEvent e) {
       if(e.getKeyCode() == KeyEvent.VK_ENTER){
            realizarConexion();
        }
       else if(e.getKeyCode() == KeyEvent.VK_ESCAPE){
            this.dispose();
       }
    }

    @Override
    public void keyReleased(KeyEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
